# Generated by Django 3.1.7 on 2021-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('active', models.BooleanField(verbose_name='active')),
                ('header_bg_color', models.CharField(blank=True, max_length=7, verbose_name='background color')),
                ('header_text_color', models.CharField(blank=True, max_length=7, verbose_name='text color')),
                ('header_link_color', models.CharField(blank=True, max_length=7, verbose_name='link color')),
                ('header_link_hover_color', models.CharField(blank=True, max_length=7, verbose_name='link hover color')),
            ],
        ),
    ]
