# Generated by Django 3.1.7 on 2021-03-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, primary_key=True, serialize=False, verbose_name='slug')),
                ('active', models.BooleanField(verbose_name='active')),
                ('branding_title', models.CharField(blank=True, max_length=50, verbose_name='title')),
                ('branding_title_use', models.BooleanField(verbose_name='use')),
                ('branding_bg_color', models.CharField(blank=True, max_length=7, verbose_name='background color')),
                ('branding_bg_color_use', models.BooleanField(verbose_name='use')),
                ('branding_text_color', models.CharField(blank=True, max_length=7, verbose_name='text color')),
                ('branding_text_color_use', models.BooleanField(verbose_name='use')),
                ('branding_link_color', models.CharField(blank=True, max_length=7, verbose_name='link color')),
                ('branding_link_color_use', models.BooleanField(verbose_name='use')),
                ('branding_link_hover_color', models.CharField(blank=True, max_length=7, verbose_name='link hover color')),
                ('branding_link_hover_color_use', models.BooleanField(verbose_name='use')),
                ('header_bg_color', models.CharField(blank=True, max_length=7, verbose_name='background color')),
                ('header_bg_color_use', models.BooleanField(verbose_name='use')),
                ('header_text_color', models.CharField(blank=True, max_length=7, verbose_name='text color')),
                ('header_text_color_use', models.BooleanField(verbose_name='use')),
                ('header_link_color', models.CharField(blank=True, max_length=7, verbose_name='link color')),
                ('header_link_color_use', models.BooleanField(verbose_name='use')),
                ('header_link_hover_color', models.CharField(blank=True, max_length=7, verbose_name='link hover color')),
                ('header_link_hover_color_use', models.BooleanField(verbose_name='use')),
                ('breadcrumbs_bg_color', models.CharField(blank=True, max_length=7, verbose_name='background color')),
                ('breadcrumbs_bg_color_use', models.BooleanField(verbose_name='use')),
                ('breadcrumbs_text_color', models.CharField(blank=True, max_length=7, verbose_name='text color')),
                ('breadcrumbs_text_color_use', models.BooleanField(verbose_name='use')),
                ('breadcrumbs_link_color', models.CharField(blank=True, max_length=7, verbose_name='link color')),
                ('breadcrumbs_link_color_use', models.BooleanField(verbose_name='use')),
                ('breadcrumbs_link_hover_color', models.CharField(blank=True, max_length=7, verbose_name='link hover color')),
                ('breadcrumbs_link_hover_color_use', models.BooleanField(verbose_name='use')),
                ('module_bg_color', models.CharField(blank=True, max_length=7, verbose_name='background color')),
                ('module_bg_color_use', models.BooleanField(verbose_name='use')),
                ('module_text_color', models.CharField(blank=True, max_length=7, verbose_name='text color')),
                ('module_text_color_use', models.BooleanField(verbose_name='use')),
                ('module_link_color', models.CharField(blank=True, max_length=7, verbose_name='link color')),
                ('module_link_color_use', models.BooleanField(verbose_name='use')),
                ('module_link_hover_color', models.CharField(blank=True, max_length=7, verbose_name='link hover color')),
                ('module_link_hover_color_use', models.BooleanField(verbose_name='use')),
            ],
        ),
    ]
