# Generated by Django 3.1.7 on 2021-03-07 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('active', models.BooleanField(verbose_name='active')),
                ('logo', models.FileField(upload_to='branding/logo/%Y/%m/%d', validators=[django.core.validators.validate_image_file_extension])),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
